### ISSUE TITLE
Missing tables when running migrate

### ISSUE THREAD

**Issue by stev-0** [jclgoodwin/bustimes.org.uk#40]
Hi, I'm trying to run your tool, and I seem to have a few missing tables after running ./manage.py migrate - e.g. operators, regions etc. I think this is causing import problems, although no errors seem to come up. Is there any reason you can think of why those tables wouldn't be in the schema?

This is the list of tables I have after successfully running migrations:

 public | agency                          | table | postgres
 public | auth_group                      | table | postgres
 public | auth_group_permissions          | table | postgres
 public | auth_permission                 | table | postgres
 public | auth_user                       | table | postgres
 public | auth_user_groups                | table | postgres
 public | auth_user_user_permissions      | table | postgres
 public | block                           | table | postgres
 public | busstops_adminarea              | table | postgres
 public | busstops_district               | table | postgres
 public | busstops_journey                | table | postgres
 public | busstops_livesource             | table | postgres
 public | busstops_locality               | table | postgres
 public | busstops_locality_adjacent      | table | postgres
 public | busstops_note                   | table | postgres
 public | busstops_note_operators         | table | postgres
 public | busstops_note_services          | table | postgres
 public | busstops_operator               | table | postgres
 public | busstops_region                 | table | postgres
 public | busstops_service                | table | postgres
 public | busstops_service_operator       | table | postgres
 public | busstops_servicedate            | table | postgres
 public | busstops_stoparea               | table | postgres
 public | busstops_stoppoint              | table | postgres
 public | busstops_stoppoint_live_sources | table | postgres
 public | busstops_stopusage              | table | postgres
 public | busstops_stopusageusage         | table | postgres
 public | django_admin_log                | table | postgres
 public | django_content_type             | table | postgres
 public | django_migrations               | table | postgres
 public | django_session                  | table | postgres
 public | fare                            | table | postgres
 public | fare_rules                      | table | postgres
 public | feed                            | table | postgres
 public | feed_info                       | table | postgres
 public | frequency                       | table | postgres
 public | route                           | table | postgres
 public | service                         | table | postgres
 public | service_date                    | table | postgres
 public | shape                           | table | postgres
 public | shape_point                     | table | postgres
 public | spatial_ref_sys                 | table | postgres
 public | stop                            | table | postgres
 public | stop_time                       | table | postgres
 public | transfer                        | table | postgres
 public | trip                            | table | postgres
 public | zone                            | table | postgres

**Comment by jclgoodwin** [comment]
That list of tables looks correct to me – I can see `busstops_operator` and `busstops_region` in there. What sort of problems are you having?

**Comment by stev-0** [comment]
My bad, the tables are there! I think I just didn't realise you had to run generate_journeys as well. I will close this as it's not relevant. I may make a few pull requests and raise the odd issue or two though. 

Thanks
